nav:
  - index.md
  - LLM Judge: llm-judge.ipynb
  - Judge Parser: llm-judge-parser.ipynb
  - RunPod Automated Judging: llm-judge-runpod-auto-v2.ipynb
  - RunPod Manual Judging: llm-judge-runpod-manual.ipynb
  - Judge Automation Script: llm_judge_automation.py
  - Academic Rubric Background: llm-as-a-judge-from-academia.md
  - Judge Rubric Definitions: sysengbench-osq-llm-judge
  - Unused Rubrics: unused-rubrics
