#!/usr/bin/env python3
"""
End-to-end metaeval pipeline test using Claude Opus 4.6 as both
inference model and judge model.

This script validates the full pipeline:
  Phase 1-3: Load existing SysEngBench data (MCQ, OSQ, variants)
  Phase 4:   Inference - Opus 4.6 agent responses (embedded)
  Phase 5:   Judging - Opus 4.6 agent evaluations (embedded)
  Phase 6:   Analysis - Position bias + MCQ vs OSQ comparison

No external API calls are made. All model responses and judgments
were generated by Claude Opus 4.6 (the agent) and embedded directly.
"""

import json
import re
import sys
import time
from datetime import datetime
from pathlib import Path

import pandas as pd
import numpy as np

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent
TEST_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = TEST_DIR / "output"
JUDGED_DIR = TEST_DIR / "judged"
MODEL_NAME = "anthropic/claude-opus-4-6"
MODEL_NAME_SANITIZED = "anthropic__claude-opus-4-6"
TIMESTAMP = datetime.now().strftime("%Y-%m-%dT%H-%M-%S.%f")
N_QUESTIONS = 4  # Questions 1-4

# Data paths
MCQ_CSV = BASE_DIR / "src" / "phase1_prep" / "sysengbench.csv"
OSQ_CSV = BASE_DIR / "src" / "phase2_conversion" / "artifacts_mcq2osq" / "sysengbench_osq_filtered.csv"
VARIANT_DIR = BASE_DIR / "src" / "phase3_variants"

# ---------------------------------------------------------------------------
# Agent-generated responses (Opus 4.6)
# ---------------------------------------------------------------------------

# MCQ answers: {variant: {question_id: answer_letter}}
# The correct answer is always at the position matching the variant letter.
MCQ_ANSWERS = {
    "a": {1: "A", 2: "A", 3: "A", 4: "A"},
    "b": {1: "B", 2: "B", 3: "B", 4: "B"},
    "c": {1: "C", 2: "C", 3: "C", 4: "C"},
    "d": {1: "D", 2: "D", 3: "D", 4: "D"},
}

# OSQ responses: {question_id: response_text}
OSQ_RESPONSES = {
    1: (
        "Uncertainty in systems engineering is a condition in which the outcomes "
        "or behavior of a system cannot be precisely predicted due to incomplete "
        "information (epistemic uncertainty) or inherent variability in the system "
        "or its environment (aleatory uncertainty). It necessitates robust design "
        "approaches and risk management strategies to accommodate unpredictable "
        "system states."
    ),
    2: (
        "Risk in systems engineering is the potential for an undesirable outcome "
        "or loss, quantified by the combination of the probability (likelihood) "
        "of an adverse event occurring and the severity (impact) of its "
        "consequences. It is a fundamental consideration in decision-making, "
        "requiring systematic identification, assessment, and mitigation "
        "throughout the system lifecycle."
    ),
    3: (
        "The two main types of uncertainty in systems engineering are epistemic "
        "uncertainty and aleatory uncertainty. Epistemic uncertainty arises from "
        "incomplete knowledge or data and can be reduced through additional "
        "research, analysis, or testing. Aleatory uncertainty is inherent "
        "randomness or natural variability in a system or process that cannot "
        "be eliminated, only characterized and managed."
    ),
    4: (
        "The primary goal of systems integration in systems engineering is to "
        "ensure that all individual system components, subsystems, and interfaces "
        "function together as a cohesive, unified whole that meets the overall "
        "system requirements and intended operational capabilities."
    ),
}

# Judge evaluations: {question_id: raw_judge_response_text}
# These follow the multi_dimensional prompt format (5 dimensions, 0-20 each).
JUDGE_RESPONSES = {
    1: json.dumps({
        "technical_accuracy": 19,
        "conceptual_understanding": 20,
        "completeness": 18,
        "clarity_organization": 19,
        "professional_relevance": 18,
        "total_score": 94,
        "justification": (
            "Technical Accuracy (19/20): The response correctly identifies "
            "uncertainty as unpredictability of system outcomes and accurately "
            "names both epistemic and aleatory uncertainty with correct "
            "definitions. Minor deduction for not explicitly linking to "
            "'system or its environment' as the INCOSE framing does. "
            "Conceptual Understanding (20/20): Demonstrates deep understanding "
            "by distinguishing the two canonical types and connecting uncertainty "
            "to the need for robust design and risk management. "
            "Completeness (18/20): Covers both sources of uncertainty "
            "(incomplete information and inherent variability) and their "
            "implications. Could have been slightly more explicit about "
            "'system outcomes or behavior' as the subject of unpredictability. "
            "Clarity & Organization (19/20): Well-structured two-sentence "
            "response with clear logical flow from definition to implication. "
            "Professional Relevance (18/20): Appropriately connects to "
            "professional practice (robust design, risk management) though "
            "could reference specific SE lifecycle contexts."
        ),
    }),
    2: json.dumps({
        "technical_accuracy": 20,
        "conceptual_understanding": 19,
        "completeness": 20,
        "clarity_organization": 19,
        "professional_relevance": 19,
        "total_score": 97,
        "justification": (
            "Technical Accuracy (20/20): Precisely defines risk as potential "
            "for undesirable outcome/loss, correctly identifies both "
            "quantification dimensions (probability/likelihood and "
            "severity/impact). Matches the canonical definition exactly. "
            "Conceptual Understanding (19/20): Shows strong understanding of "
            "risk as a probabilistic concept requiring systematic management. "
            "Minor deduction: could more explicitly contrast risk with "
            "certainty or guaranteed outcomes. "
            "Completeness (20/20): Addresses all required elements: what risk "
            "represents (potential for loss), how it is quantified (probability "
            "and severity), and its role in SE (decision-making, lifecycle). "
            "Clarity & Organization (19/20): Clear two-sentence structure that "
            "moves from definition to application. Professional language "
            "throughout. "
            "Professional Relevance (19/20): Strong practical framing with "
            "references to systematic identification, assessment, mitigation, "
            "and lifecycle context."
        ),
    }),
    3: json.dumps({
        "technical_accuracy": 20,
        "conceptual_understanding": 20,
        "completeness": 19,
        "clarity_organization": 20,
        "professional_relevance": 18,
        "total_score": 97,
        "justification": (
            "Technical Accuracy (20/20): Correctly names both epistemic and "
            "aleatory uncertainty with precise definitions. Epistemic is "
            "correctly identified as reducible via additional knowledge; "
            "aleatory as inherent and irreducible. "
            "Conceptual Understanding (20/20): Demonstrates excellent "
            "understanding of the fundamental distinction between knowledge "
            "uncertainty and inherent variability, correctly noting one can "
            "be reduced and the other only managed. "
            "Completeness (19/20): All four rubric elements present (both "
            "names, both definitions with reducibility). Could have mentioned "
            "specific examples of each type for maximum completeness. "
            "Clarity & Organization (20/20): Three clear sentences with "
            "excellent parallel structure: introduction, epistemic definition, "
            "aleatory definition. "
            "Professional Relevance (18/20): Accurate technical framing. "
            "Could strengthen by mentioning how this distinction affects "
            "SE decision-making or risk analysis."
        ),
    }),
    4: json.dumps({
        "technical_accuracy": 19,
        "conceptual_understanding": 19,
        "completeness": 18,
        "clarity_organization": 20,
        "professional_relevance": 18,
        "total_score": 94,
        "justification": (
            "Technical Accuracy (19/20): Correctly identifies the primary "
            "goal as ensuring components function together as a cohesive "
            "whole. Appropriately mentions subsystems and interfaces. "
            "Minor deduction for not explicitly using 'interoperability' "
            "terminology. "
            "Conceptual Understanding (19/20): Shows clear understanding "
            "that integration is about the whole-system perspective, not "
            "just connecting parts. Mentions meeting system requirements. "
            "Completeness (18/20): Covers the core goal well. Could "
            "strengthen by explicitly distinguishing integration from "
            "other goals (cost reduction, documentation, individual "
            "component performance). "
            "Clarity & Organization (20/20): Single concise sentence "
            "that clearly and directly answers the question. "
            "Professional Relevance (18/20): Good mention of operational "
            "capabilities and system requirements. Could reference "
            "verification/validation or integration testing."
        ),
    }),
}


# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

def print_phase(phase_num: int, title: str) -> None:
    """Print a phase header."""
    print(f"\n{'='*80}")
    print(f"  PHASE {phase_num}: {title}")
    print(f"{'='*80}\n")


def print_success(msg: str) -> None:
    print(f"  [PASS] {msg}")


def print_fail(msg: str) -> None:
    print(f"  [FAIL] {msg}")


def build_mcq_prompt(row: pd.Series) -> str:
    """Build MCQ prompt in lm-eval format."""
    return (
        "Given the following question and four candidate answers (A, B, C and D), "
        "choose the best answer. Your response must consist solely of the single "
        "letter corresponding to the best answer, chosen from one of A, B, C or D. "
        "Any response other than a single letter (A, B, C, or D) will be considered "
        f"invalid.\nQuestion: {row['question']}\n"
        f"A. {row['choiceA']}\nB. {row['choiceB']}\n"
        f"C. {row['choiceC']}\nD. {row['choiceD']}\nAnswer:"
    )


def build_osq_prompt(row: pd.Series) -> str:
    """Build OSQ prompt in lm-eval format."""
    prompt_field = row.get("osq_prompt", row.get("question", ""))
    return (
        "Given the following question, answer it to the best of your ability. "
        "Your response should generally be between 2 and 4 sentences, but may "
        "be longer if a more detailed solution is appropriate.\n"
        f"{prompt_field}\nAnswer:"
    )


def write_lm_eval_results(
    output_dir: Path,
    task_name: str,
    accuracy: float,
    n_samples: int,
    timestamp: str,
) -> Path:
    """Write a lm-eval compatible results.json file."""
    output_dir.mkdir(parents=True, exist_ok=True)

    results = {
        "results": {
            task_name: {
                "alias": task_name,
                "exact_match,strict-match": accuracy,
                "exact_match_stderr,strict-match": 0.0,
            }
        },
        "group_subtasks": {task_name: []},
        "configs": {
            task_name: {
                "task": task_name,
                "output_type": "generate_until",
                "num_fewshot": 0,
                "metric_list": [
                    {
                        "metric": "exact_match",
                        "aggregation": "mean",
                        "higher_is_better": True,
                    }
                ],
                "metadata": {
                    "version": 1.0,
                    "model": MODEL_NAME,
                },
            }
        },
        "versions": {task_name: 1.0},
        "n-shot": {task_name: 0},
        "higher_is_better": {task_name: {"exact_match": True}},
        "n-samples": {
            task_name: {"original": 1144, "effective": n_samples}
        },
        "config": {
            "model": "anthropic-chat-completions",
            "model_args": f"model={MODEL_NAME}",
            "batch_size": 1,
            "batch_sizes": [],
            "device": None,
            "limit": float(n_samples),
        },
        "model_name": MODEL_NAME,
        "model_name_sanitized": MODEL_NAME_SANITIZED,
        "lm_eval_version": "0.4.9.1",
        "date": time.time(),
        "total_evaluation_time_seconds": "0.0",
    }

    results_path = output_dir / f"results_{timestamp}.json"
    with open(results_path, "w") as f:
        json.dump(results, f, indent=2)

    return results_path


def write_lm_eval_samples(
    output_dir: Path,
    task_name: str,
    samples: list[dict],
    timestamp: str,
) -> Path:
    """Write a lm-eval compatible samples.jsonl file."""
    output_dir.mkdir(parents=True, exist_ok=True)

    samples_path = output_dir / f"samples_{task_name}_{timestamp}.jsonl"
    with open(samples_path, "w") as f:
        for sample in samples:
            f.write(json.dumps(sample) + "\n")

    return samples_path


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

def main() -> int:
    results_summary = {}
    start_time = time.time()

    print("\n" + "#" * 80)
    print("  METAEVAL FULL PIPELINE TEST")
    print(f"  Inference Model: {MODEL_NAME}")
    print(f"  Judge Model:     {MODEL_NAME}")
    print(f"  Questions:       {N_QUESTIONS}")
    print(f"  Date:            {datetime.now().isoformat()}")
    print("#" * 80)

    # -----------------------------------------------------------------------
    # PHASE 1-3: Load existing data
    # -----------------------------------------------------------------------
    print_phase(1, "LOAD BENCHMARK DATA (Phases 1-3)")

    # Load MCQ data
    mcq_df = pd.read_csv(MCQ_CSV)
    mcq_4 = mcq_df[mcq_df["Question ID"].isin(range(1, N_QUESTIONS + 1))].copy()
    print_success(f"Loaded MCQ benchmark: {len(mcq_df)} total, {len(mcq_4)} selected")

    # Load OSQ data
    osq_df = pd.read_csv(OSQ_CSV)
    osq_4 = osq_df[osq_df["Question ID"].isin(range(1, N_QUESTIONS + 1))].copy()
    print_success(f"Loaded OSQ data: {len(osq_df)} total, {len(osq_4)} selected")

    # Load variant data
    variant_dfs = {}
    for variant in ["a", "b", "c", "d"]:
        vdf = pd.read_csv(VARIANT_DIR / f"sysengbench_{variant}.csv")
        variant_dfs[variant] = vdf[
            vdf["Question ID"].isin(range(1, N_QUESTIONS + 1))
        ].copy()
        print_success(
            f"Loaded variant {variant.upper()}: "
            f"{len(vdf)} total, {len(variant_dfs[variant])} selected"
        )

    results_summary["phase_1_3"] = "PASS"

    # Print sample question
    print(f"\n  Sample Question (ID=1):")
    row = mcq_4.iloc[0]
    print(f"    {row['question'][:80]}...")
    print(f"    Correct answer: {row['answer']}")

    # -----------------------------------------------------------------------
    # PHASE 4: Inference (agent-generated, write lm-eval format)
    # -----------------------------------------------------------------------
    print_phase(4, "INFERENCE (Opus 4.6 Agent Responses)")

    # --- MCQ Inference ---
    print("  --- MCQ Inference (4 variants x 4 questions = 16 responses) ---\n")

    mcq_results_by_variant = {}

    for variant in ["a", "b", "c", "d"]:
        vdf = variant_dfs[variant]
        task_name = f"sysengbench-{variant}" if variant != "a" else "sysengbench"
        # Use sysengbench (no suffix) for variant a to match lm-eval convention
        # Actually lm-eval uses sysengbench-a for variant a too in our setup
        task_name = f"sysengbench-{variant}"

        samples = []
        correct_count = 0

        for idx, (_, row) in enumerate(vdf.iterrows()):
            qid = row["Question ID"]
            answer = MCQ_ANSWERS[variant][qid]
            target = row["answer"]
            is_correct = answer.strip().upper() == target.strip().upper()
            if is_correct:
                correct_count += 1

            prompt_text = build_mcq_prompt(row)

            sample = {
                "doc_id": idx,
                "doc": {
                    "Question ID": int(qid),
                    "Tags": row.get("Tags", ""),
                    "INCOSE Handbook Category": row.get(
                        "INCOSE Handbook Category", ""
                    ),
                    "question": row["question"],
                    "choiceA": row["choiceA"],
                    "choiceB": row["choiceB"],
                    "choiceC": row["choiceC"],
                    "choiceD": row["choiceD"],
                    "answer": target,
                    "label": int(row.get("label", 0)),
                    "Justification": row.get("Justification", ""),
                },
                "target": target,
                "arguments": {
                    "gen_args_0": {
                        "arg_0": json.dumps(
                            [{"content": prompt_text, "role": "user"}]
                        ),
                        "arg_1": {
                            "until": [],
                            "max_gen_toks": 10,
                            "temperature": 0.0,
                        },
                    }
                },
                "resps": [[answer]],
                "filtered_resps": [answer],
                "filter": "strict-match",
                "metrics": ["exact_match"],
                "doc_hash": "",
                "prompt_hash": "",
                "target_hash": "",
                "exact_match": 1.0 if is_correct else 0.0,
            }
            samples.append(sample)

        accuracy = correct_count / len(samples) if samples else 0.0
        mcq_results_by_variant[variant] = {
            "accuracy": accuracy,
            "correct": correct_count,
            "total": len(samples),
            "samples": samples,
        }

        # Write lm-eval output
        model_dir = OUTPUT_DIR / task_name / MODEL_NAME_SANITIZED
        write_lm_eval_results(model_dir, task_name, accuracy, len(samples), TIMESTAMP)
        write_lm_eval_samples(model_dir, task_name, samples, TIMESTAMP)

        status = "PASS" if accuracy == 1.0 else "PARTIAL"
        print_success(
            f"Variant {variant.upper()}: {correct_count}/{len(samples)} correct "
            f"({accuracy:.0%}) [{status}]"
        )

    # --- OSQ Inference ---
    print("\n  --- OSQ Inference (4 open-ended responses) ---\n")

    osq_samples = []
    for idx, (_, row) in enumerate(osq_4.iterrows()):
        qid = row["Question ID"]
        response = OSQ_RESPONSES[qid]
        prompt_text = build_osq_prompt(row)

        sample = {
            "doc_id": idx,
            "doc": {
                "Question ID": int(qid),
                "Tags": row.get("Tags", ""),
                "INCOSE Handbook Category": row.get(
                    "INCOSE Handbook Category", ""
                ),
                "question": row["question"],
                "choiceA": row.get("choiceA", ""),
                "choiceB": row.get("choiceB", ""),
                "choiceC": row.get("choiceC", ""),
                "choiceD": row.get("choiceD", ""),
                "answer": row.get("answer", ""),
                "label": int(row.get("label", 0)),
                "Justification": row.get("Justification", ""),
                "osq_prompt": row.get("osq_prompt", ""),
                "expected_answer": row.get("expected_answer", ""),
                "full_credit_criteria": row.get("full_credit_criteria", ""),
                "partial_credit_criteria": row.get(
                    "partial_credit_criteria", ""
                ),
                "no_credit_criteria": row.get("no_credit_criteria", ""),
                "blooms_level": row.get("blooms_level", ""),
                "blooms_justification": row.get("blooms_justification", ""),
            },
            "target": row.get("expected_answer", ""),
            "arguments": {
                "gen_args_0": {
                    "arg_0": json.dumps(
                        [{"content": prompt_text, "role": "user"}]
                    ),
                    "arg_1": {
                        "until": [],
                        "max_gen_toks": 500,
                        "temperature": 0.0,
                    },
                }
            },
            "resps": [[response]],
            "filtered_resps": [response],
            "filter": "none",
            "metrics": ["exact_match"],
            "doc_hash": "",
            "prompt_hash": "",
            "target_hash": "",
            "exact_match": 0.0,  # OSQ exact match is always 0 (needs judge)
        }
        osq_samples.append(sample)
        print_success(f"Q{qid} response ({len(response)} chars): {response[:60]}...")

    # Write OSQ lm-eval output
    osq_model_dir = OUTPUT_DIR / "sysengbench-osq" / MODEL_NAME_SANITIZED
    write_lm_eval_results(osq_model_dir, "sysengbench-osq", 0.0, len(osq_samples), TIMESTAMP)
    write_lm_eval_samples(osq_model_dir, "sysengbench-osq", osq_samples, TIMESTAMP)

    results_summary["phase_4"] = "PASS"

    # -----------------------------------------------------------------------
    # PHASE 4.5: Verify lm-eval output can be parsed by metaeval harness
    # -----------------------------------------------------------------------
    print("\n  --- Verifying lm-eval output format (LMEvalParser) ---\n")

    from metaeval.harness import LMEvalParser

    # Test MCQ parsing
    for variant in ["a", "b", "c", "d"]:
        task_name = f"sysengbench-{variant}"
        model_dir = OUTPUT_DIR / task_name / MODEL_NAME_SANITIZED
        parser = LMEvalParser(model_dir)
        run = parser.parse()
        print_success(
            f"LMEvalParser read variant {variant.upper()}: "
            f"task={run.task}, model={run.model}, "
            f"format={run.format}, samples={run.n_samples}, "
            f"accuracy={run.accuracy:.0%}"
        )

    # Test OSQ parsing
    parser = LMEvalParser(osq_model_dir)
    run = parser.parse()
    osq_results_parsed = parser.to_osq_results()
    print_success(
        f"LMEvalParser read OSQ: task={run.task}, "
        f"format={run.format}, samples={run.n_samples}"
    )
    for r in osq_results_parsed:
        print(f"    OSQ Q{r.question_id}: response={r.model_response[:50]}...")

    # -----------------------------------------------------------------------
    # PHASE 5: Judging (agent-generated, parsed by metaeval scorer)
    # -----------------------------------------------------------------------
    print_phase(5, "LLM-AS-A-JUDGE (Opus 4.6 Agent Evaluations)")

    from metaeval.judge.scorer import parse_judgment

    JUDGED_DIR.mkdir(parents=True, exist_ok=True)
    judged_path = JUDGED_DIR / "judged.jsonl"

    judged_results = []

    for osq_result in osq_results_parsed:
        qid = osq_result.question_id
        raw_judgment = JUDGE_RESPONSES[qid]

        # Parse using metaeval's scorer
        parsed = parse_judgment(raw_judgment)

        judgment_record = {
            "question_id": qid,
            "model": MODEL_NAME_SANITIZED,
            "judge_model": MODEL_NAME,
            "prompt_style": "multi_dimensional",
            "scores": parsed.scores.to_dict() if parsed.scores else None,
            "total_score": parsed.total_score,
            "justification": parsed.justification,
            "credit_level": parsed.credit_level,
            "parse_success": parsed.parse_success,
            "parse_errors": parsed.parse_errors,
            "from_cache": False,
        }
        judged_results.append(judgment_record)

        status = "PASS" if parsed.parse_success else "FAIL"
        if parsed.scores:
            dims = parsed.scores.to_dict()
            dim_str = ", ".join(f"{k[:4]}={v}" for k, v in dims.items())
            print_success(
                f"Q{qid}: total={parsed.total_score}/100 "
                f"credit={parsed.credit_level} [{status}]"
            )
            print(f"         Dimensions: {dim_str}")
        else:
            print_fail(
                f"Q{qid}: parse failed - {parsed.parse_errors}"
            )

    # Write judged output
    with open(judged_path, "w") as f:
        for record in judged_results:
            f.write(json.dumps(record) + "\n")

    all_parsed = all(r["parse_success"] for r in judged_results)
    results_summary["phase_5"] = "PASS" if all_parsed else "FAIL"
    print(f"\n  Judged {len(judged_results)} responses -> {judged_path}")
    print(f"  All parsed successfully: {all_parsed}")

    # -----------------------------------------------------------------------
    # PHASE 6a: Position Bias Analysis
    # -----------------------------------------------------------------------
    print_phase(6, "ANALYSIS")

    print("  --- 6a: Position Bias Analysis ---\n")

    from metaeval.bias.detection import PositionBiasAnalyzer

    # Build DataFrame from MCQ results
    bias_rows = []
    for variant, data in mcq_results_by_variant.items():
        for sample in data["samples"]:
            bias_rows.append({
                "model": MODEL_NAME_SANITIZED,
                "variant": variant.upper(),
                "question_id": sample["doc"]["Question ID"],
                "is_correct": int(sample["exact_match"]),
            })

    bias_df = pd.DataFrame(bias_rows)
    print_success(f"Built bias DataFrame: {len(bias_df)} rows")
    print(f"    Columns: {list(bias_df.columns)}")
    print(f"    Models: {bias_df['model'].unique().tolist()}")
    print(f"    Variants: {sorted(bias_df['variant'].unique().tolist())}")

    try:
        analyzer = PositionBiasAnalyzer(bias_df)
        bias_reports = analyzer.analyze_all_models()

        for model, report in bias_reports.items():
            acc = report.accuracy_by_position
            print_success(
                f"Model: {model}\n"
                f"         Overall accuracy: {report.overall_accuracy:.0%}\n"
                f"         By position: "
                + ", ".join(f"{k}={v:.0%}" for k, v in sorted(acc.items()))
                + f"\n         Significant bias: {report.has_significant_bias}"
            )

        results_summary["phase_6a_bias"] = "PASS"
    except Exception as e:
        print_fail(f"Bias analysis failed: {e}")
        import traceback
        traceback.print_exc()
        results_summary["phase_6a_bias"] = f"FAIL: {e}"

    # -----------------------------------------------------------------------
    # PHASE 6b: MCQ vs OSQ Comparison
    # -----------------------------------------------------------------------
    print("\n  --- 6b: MCQ vs OSQ Format Comparison ---\n")

    from metaeval.compare.analysis import FormatComparator

    # Build comparison DataFrame
    # MCQ score = average accuracy across variants per question
    mcq_scores = {}
    for variant, data in mcq_results_by_variant.items():
        for sample in data["samples"]:
            qid = sample["doc"]["Question ID"]
            if qid not in mcq_scores:
                mcq_scores[qid] = []
            mcq_scores[qid].append(sample["exact_match"])

    compare_rows = []
    for qid in range(1, N_QUESTIONS + 1):
        mcq_avg = np.mean(mcq_scores.get(qid, [0.0]))
        # Find matching judged result
        osq_score = 0.0
        for jr in judged_results:
            if jr["question_id"] == qid:
                osq_score = float(jr["total_score"])
                break

        compare_rows.append({
            "model": MODEL_NAME_SANITIZED,
            "question_id": qid,
            "mcq_score": mcq_avg,
            "osq_score": osq_score,
        })

    compare_df = pd.DataFrame(compare_rows)
    print_success(f"Built comparison DataFrame: {len(compare_df)} rows")
    print(f"    MCQ scores: {compare_df['mcq_score'].tolist()}")
    print(f"    OSQ scores: {compare_df['osq_score'].tolist()}")

    try:
        comparator = FormatComparator(compare_df)
        compare_reports = comparator.analyze_all_models()

        for model, report in compare_reports.items():
            pearson = report.correlations.get("pearson")
            pearson_str = (
                f"{pearson.coefficient:.3f}" if pearson else "N/A"
            )
            print_success(
                f"Model: {model}\n"
                f"         MCQ accuracy: {report.mcq_accuracy:.0%}\n"
                f"         OSQ normalized: {report.osq_normalized:.0%}\n"
                f"         Pearson correlation: {pearson_str}\n"
                f"         N questions: {report.n_questions}"
            )

        results_summary["phase_6b_compare"] = "PASS"
    except Exception as e:
        print_fail(f"Comparison analysis failed: {e}")
        import traceback
        traceback.print_exc()
        results_summary["phase_6b_compare"] = f"FAIL: {e}"

    # -----------------------------------------------------------------------
    # FINAL SUMMARY
    # -----------------------------------------------------------------------
    elapsed = time.time() - start_time

    print(f"\n{'#'*80}")
    print("  PIPELINE TEST SUMMARY")
    print(f"{'#'*80}\n")

    all_pass = True
    for phase, status in results_summary.items():
        indicator = "[PASS]" if status == "PASS" else "[FAIL]"
        if status != "PASS":
            all_pass = False
        print(f"  {indicator} {phase}: {status}")

    print(f"\n  Total time: {elapsed:.1f}s")
    print(f"  Output directory: {OUTPUT_DIR}")
    print(f"  Judged directory: {JUDGED_DIR}")

    # List output files
    print(f"\n  Generated files:")
    for p in sorted(OUTPUT_DIR.rglob("*")):
        if p.is_file():
            print(f"    {p.relative_to(TEST_DIR)}")
    for p in sorted(JUDGED_DIR.rglob("*")):
        if p.is_file():
            print(f"    {p.relative_to(TEST_DIR)}")

    if all_pass:
        print(f"\n  RESULT: ALL PHASES PASSED")
    else:
        print(f"\n  RESULT: SOME PHASES FAILED")

    print(f"{'#'*80}\n")

    return 0 if all_pass else 1


if __name__ == "__main__":
    sys.exit(main())
